### ISSUE TITLE
Make the AFK message "You are now AFK." optional in config

### ISSUE THREAD

**Issue by Stray216** [DBTDerpbox/Color-Changer#1]
When you play a lot of Minecraft with this datapack enabled, after a while this message is all you see in chat.
Just a very lot of "You are now AFK." messages.

Can you make it optional?

**Comment by DBTDerpbox** [comment]
sorry for not responding to this sooner, life has been a mess and i didnt notice this
yeah i can probably do this

**Comment by DBTDerpbox** [comment]
Will be included in the next release, sorry for taking so long to implement this
