### ISSUE TITLE
is an update to 1.21.3 planned?

### ISSUE THREAD

**Issue by Baddy60** [DBTDerpbox/Color-Changer#2]
Would be great if it is :) Thanks!

**Comment by DBTDerpbox** [comment]
Life has been extremely busy since June for me so I haven't gotten around to it, does the pack not work on 1.21.3?

**Comment by DBTDerpbox** [comment]
Just checked, it is partially broken, I'll upload a fix when I can

**Comment by DBTDerpbox** [comment]
Finished, see https://modrinth.com/datapack/color-changer-datapack/version/1.2.4
